answers = {
        "Julius Caesar": "Oh that's a good question, well, It's difficult to choose a favorite battle from my long and illustrious career, but there are a few that stand out as particularly memorable.One of my most significant victories was the Battle of Alesia, which took place in 52 BC. At this battle, I led my forces against a large and well-fortified Gallic army. Despite being heavily outnumbered, my tactics allowed me to encircle and defeat the enemy, effectively ending the Gallic Wars and securing my position in Rome.",
        "Napoleon": "Oh that's a good question, well, As a military strategist and commander, I have fought in many battles, each with its own challenges and victories. While I do not have a single favorite battle, there are a few that I hold in high regard. One of the battles that I consider to be a significant turning point in my military career is the Battle of Austerlitz. The battle was fought on December 2, 1805, against a combined army of Russian and Austrian forces. I consider this battle to be one of my greatest victories, as my troops were able to outmaneuver and defeat a much larger enemy force. Another battle that holds a special place in my memory is the Battle of Marengo, which took place on June 14, 1800. In this battle, my troops were able to achieve a decisive victory against the Austrians in Italy, securing my hold on the region.",
        "Queen Elizabeth I": "Oh that's a good question, well, While I am known for my diplomatic skills and my efforts to maintain peace, there were times when military conflict was necessary to protect my realm and my people.One of the battles that I hold in high regard is the Battle of Tilbury, which took place in 1588. At this battle, the English forces, under the command of my trusted general, Lord Howard of Effingham, successfully repelled the invading Spanish Armada. I am immensely proud of this victory, which secured England's place as a major naval power and protected my people from the threat of invasion.",
        "Cleopatra": "Oh that's a good question, well, While I am not known for my military prowess, I was intimately involved with two of the most famous military leaders in history: Julius Caesar and Mark Antony. As such, I was often present at battles and played an important role in the strategies that were employed. One of the battles that I consider to be particularly significant is the Battle of Actium, which took place in 31 BC. This battle was fought between the forces of Mark Antony and myself, against those of Octavian (who later became the Emperor Augustus). While my forces were ultimately defeated, this battle marked a turning point in Roman history, as it paved the way for the establishment of the Roman Empire."
    }

characters = {
        "Julius Caesar": "Salve I'm Julius Cesar. And now I'm going to tell you my story.",
        "Napoleon": "Bonjour, I am Napoleon Bonaparte, Emperor of the French and one of the greatest military commanders in history, known for my strategic genius and my ambitious reforms that transformed France and Europe, and I am here to speak with you.",
        "Queen Elizabeth I": "Hello there, I am Queen Elizabeth II, Queen of the United Kingdom and the Commonwealth Realms, Defender of the Faith, and Head of the Commonwealth, and I am pleased to make your acquaintance. You will listen to my story.",
        "Cleopatra": "Hi, my name is Cleopatra ruler of Egypt and I am here to tell you my story.",
    }